#!/usr/bin/env python3
"""PCC core ABI -> Zilog EPA register operations.

CPU template encodings: Z8000 CPU Technical Manual section 6.8.
EPU-defined operation fields: preserved fpe.z8k decoder/toptab, with the
same single/double precision fields as CP/M's TestFloat harness.
Only r0-r3,r8,r9 are clobbered. EPU registers are caller-clobbered.
"""
from pathlib import Path
import sys

lines = ['! Generated by tools/fpe/wrappers.py', '\t.text']
def emit(s): lines.extend(s.splitlines())
def start(name): emit('\t.globl _'+name+'\n_'+name+':')
def load(arg, epureg=0, words=4, operation=0x8000):
    emit(f'\tld r8,{arg}(sp)')
    for i in range(words): emit(f'\tld r{i},{2*i}(r8)')
    emit(f'\t.word {0x8f08+16*epureg},{operation+words-1}')
def store(words=4, operation=0x8000):
    emit(f'\t.word 0x8f00,{operation+words-1}\n\tld r8,2(sp)')
    for i in range(words): emit(f'\tld {2*i}(r8),r{i}')
    emit('\tret')
for name,op in [('fpeadd',0x6280),('fpemul',0x62b0),('fpediv',0x62a0)]:
    start(name);load(4);load(6,2)
    emit(f'\t.word 0x8e04,{op}');store()
start('fpeftod');load(4,words=2);store()
start('fpedtof');load(4);store(words=2)
start('fpi64');load(4,operation=0x8020);store()
start('fpto64');load(4);store(operation=0x8040)
start('fpcmp');load(2);load(4,2)
emit('\t.word 0x8e00,0x4210\n\tld r0,#0\n\tldctlb rl0,flags\n\tret')
Path(sys.argv[1]).write_text('\n'.join(lines)+'\n')
